### ISSUE TITLE
Game says its outdated, even if i just updated

### ISSUE THREAD

**Issue by ignGioo** [Quantizr/DungeonRoomsMod#10]
I recently downloaded the new version and it still says I'm using an outdated version
![image](https://user-images.githubusercontent.com/100830473/156516917-c33fa991-54c0-4f49-878f-a9896fa86a48.png)
![image](https://user-images.githubusercontent.com/100830473/156516993-e5c403af-d7d1-45e5-9f1a-95f486a561d4.png)

**Comment by abuserightclick** [comment]
redownload the mod, issue has been fixed
