### ISSUE TITLE
the game is very smotth instantly after pressing "F3"

### ISSUE THREAD

**Issue by Cengokill** [Quantizr/DungeonRoomsMod#15]
Sometimes, I'm lagging A LOT when I use this mod inside a dungeon.
For example (the most common example that happened many times), before to start the dungeon in front of the NPC, the dungeon timer start and when it's 0, I'm at 1 or 2 fps.

But when I click on "F3" key, the game is instantly very smooth.

**Comment by yanickrochon** [comment]
For me, everything dies in the parkour room (orange). I've tried F3, and it still lags, but the room is now doable, at least. Though I must be careful of the lag, sometimes. I have no idea why it lags so much in that room, perhaps because of the 3 moving crushers.

**Comment by Quantizr** [comment]
If this is still an problem, please reopen the issue.
