### ISSUE TITLE
nothing happens when I open minecraft

### ISSUE THREAD

**Issue by nerd35789** [Quantizr/DungeonRoomsMod#19]
I use forge launcher to launch minecraft and moved the files of dungeonroomsmod into the .minecraft --> mods folder.  When I launch Minecraft I have the added mods button but nothing actually changes other than that.  I also use a Chromebook to play minecraft.

**Comment by X-Y0u** [comment]
then you goted ratted

**Comment by Quantizr** [comment]
> I use forge launcher to launch minecraft and moved the files of dungeonroomsmod into the .minecraft --> mods folder. When I launch Minecraft I have the added mods button but nothing actually changes other than that. I also use a Chromebook to play minecraft.

Please make sure you downloaded the correct file [Dungeon_Rooms-3.3.2.jar](https://github.com/Quantizr/DungeonRoomsMod/releases/download/v3.3.2/Dungeon_Rooms-3.3.2.jar) and not the entirety of the source code.

Join our Discord: https://discord.gg/7B5RbsArYK if you still need help in the future
