### ISSUE TITLE
Downloading this Installed a RAT on my Computer

### ISSUE THREAD

**Issue by BobTheProdigy** [Quantizr/DungeonRoomsMod#20]
Please do not download this, it is not worth getting ratted. Just get an official mod. Github is a VERY common place for ratters to advertise regular mods, but put their own RAT file in along with the regular mod.

**Comment by lj-dunphy** [comment]
This mod contains no RATs, the source code has been thoroughly reviewed by many third-parties and you can look through it yourself if you'd like. You downloaded the rat likely from somewhere else, whether that be another mod, a virus, or a mod impersonating this one (someone with a name similar to Quantizr, ex: Quantizer or QuantIzr).

**Comment by BobTheProdigy** [comment]
hmmmmm... :suspect:

**Comment by Quantizr** [comment]
As @cold-carmel stated, please make sure you downloaded the mod from this GitHub page and not one of the impersonators. Our official Discord with nearly 40k members links to this GitHub
