### ISSUE TITLE
waypoints turn off automatically with no way to turn back on after blood room is cleared

### ISSUE THREAD

**Issue by fartass69** [Quantizr/DungeonRoomsMod#5]
as the title say the waypoints turn off automatically with no way to turn back on after blood room is cleared and this is a problem especially for people who use party finder as people clear blood room before doing secrets alot of the time for the extra stats the blessings give so but i cant do any of them after the blood room is cleared, pls fix

**Comment by QuotaGamer** [comment]
lets hope this is fixed soon

**Comment by Eejit43** [comment]
fixed in [v3.30](https://github.com/Quantizr/DungeonRoomsMod/releases/tag/v3.3.0)

**Comment by Quantizr** [comment]
Closing old issues, if anyone from the future sees this, please update to latest version if you still have this issue
