### ISSUE TITLE
Mod is not working

### ISSUE THREAD

**Issue by ocyangaming** [Quantizr/DungeonRoomsMod#8]
Me and my friend have the same issue where the mod says 
"No matching room detected this mod might not have data for this room"
It dosn't matter wich room i am in. it says the same thing everywhere.

**Comment by lj-dunphy** [comment]
This is currently a problem on Hypixel's end and there is no current fix for this issue. There may be a way to accommodate for this by editing the way rooms are detected and in that case, we will have to wait for risk_ to update the mod soon tm.
